### ISSUE TITLE
Issue with response in translation

### ISSUE THREAD

**Issue by fonteijne** [softvar/translatr#13]
Currently every translation 'translates' to the following: 
```html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">```

Tried resetting the data (destroying the cookie I guess), but unfortunately this did not help. 
![Translatr___Home](https://user-images.githubusercontent.com/1511257/82879305-0ee60b00-9f3d-11ea-8944-e4815724537b.png)

**Comment by fonteijne** [comment]
My addBlocker blocks the popover message at the bottom of the screen. 
That's why I missed the message:

> The translation service is currently down for maintenance. Please wait for sometime. Inconvenience is deeply regretted.

**Comment by softvar** [comment]
Sorry for the inconvenience faced. It's fixed now :)
Enjoy the web-app 👍
