### ISSUE TITLE
Service is broken :(

### ISSUE THREAD

**Issue by Jacco-V** [softvar/translatr#14]
Hi,

I recently noticed the service has broken down. I'm guessing some backend response has changed, causing the translations to break down.

all translation request result in the following response:

```
German: html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
Spanish: html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
French: html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"> 
```

**Comment by softvar** [comment]
Sorry for the inconvenience faced. It's fixed now :)
Enjoy the web-app 👍
